/*
 * Copyright 2024 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef EINO_CPP_ADK_REACT_H_
#define EINO_CPP_ADK_REACT_H_

// ReAct (Reasoning + Acting) Pattern Implementation
// ==================================================
// Implements the ReAct agent pattern using Compose Graph framework.
// Fully aligned with eino/flow/agent/react/react.go implementation.
//
// ReAct Flow:
// 1. Agent: ChatModel reasons and decides to call tools or respond
// 2. Tools: Execute called tools (if any)
// 3. Loop: Return to Agent with tool results until complete
//
// This pattern enables iterative reasoning where the agent can:
// - Think through problems step by step
// - Call tools to gather information
// - Refine its understanding based on tool results
// - Provide final answer when ready

#include "types.h"
#include "chat_model_agent.h"
#include "../compose/graph.h"
#include "../compose/tool_node.h"
#include "../components/model.h"
#include "../schema/message.h"
#include <memory>
#include <functional>
#include <map>
#include <string>
#include <vector>

namespace eino {
namespace adk {

// =============================================================================
// State Structures
// Aligns with: eino/flow/agent/react/react.go:31-37
// =============================================================================

// ReactState stores execution state during ReAct loop
// Aligns with: state struct in react.go:31-34
struct ReactState {
    // Messages stores the conversation history
    std::vector<schema::Message> messages;
    
    // ReturnDirectlyToolCallID stores the ID of the return_directly tool call
    // When non-empty, the agent should stop and return this tool's result directly
    std::string return_directly_tool_call_id;
    
    // ToolGenActions maps step/tool name to the action generated by LLM
    // Used to track which tools were called during reasoning
    std::map<std::string, std::shared_ptr<AgentAction>> tool_gen_actions;
    
    // AgentName is the name of the agent (for logging/debugging)
    std::string agent_name;
    
    // AgentToolInterruptData stores interrupt data for agent tools
    // Key: tool call id, Value: interrupt info
    struct AgentToolInterruptInfo {
        std::shared_ptr<AgentEvent> last_event;
        std::vector<uint8_t> data;
    };
    std::map<std::string, std::shared_ptr<AgentToolInterruptInfo>> agent_tool_interrupt_data;
    
    ReactState() = default;
};

// =============================================================================
// Type Aliases
// =============================================================================

// MessageModifier modifies messages before passing to model
// Aligns with: MessageModifier in react.go:50-51
using MessageModifier = std::function<
    std::vector<schema::Message>(void* ctx, const std::vector<schema::Message>& input)>;

// StreamToolCallChecker checks if stream output contains tool calls
// Aligns with: StreamToolCallChecker in react.go:84-95
using StreamToolCallChecker = std::function<
    std::tuple<bool, std::string>(
        void* ctx,
        std::shared_ptr<schema::StreamReader<schema::Message>> sr)>;

// =============================================================================
// ReactConfig - Configuration for ReAct Agent
// Aligns with: AgentConfig in react.go:53-122
// =============================================================================

struct ReactConfig {
    // ToolCallingModel is the chat model with tool calling capability
    // Aligns with: ToolCallingModel in react.go:55-56
    components::ToolCallingChatModel* model = nullptr;
    
    // ToolsConfig specifies available tools and their configuration
    // Aligns with: ToolsConfig in react.go:61
    compose::ToolsNodeConfig* tools_config = nullptr;
    
    // MessageModifier modifies input messages before model is called
    // Useful for adding system prompts or other messages
    // Aligns with: MessageModifier in react.go:63-65
    MessageModifier message_modifier = nullptr;
    
    // MessageRewriter modifies messages in state before ChatModel is called
    // Useful for compressing message history to fit context window
    // NOTE: If both MessageModifier and MessageRewriter are set,
    // MessageRewriter is called before MessageModifier
    // Aligns with: MessageRewriter in react.go:67-72
    MessageModifier message_rewriter = nullptr;
    
    // MaxStep limits the number of steps in pregel execution
    // Default: 12 (node count + 10)
    // Aligns with: MaxStep in react.go:74-76
    int max_step = 22;
    
    // ToolReturnDirectly specifies tools that return results directly
    // When these tools are called, agent stops and returns their result
    // Key: tool name, Value: true if should return directly
    // Aligns with: ToolReturnDirectly in react.go:78-80
    std::map<std::string, bool> tools_return_directly;
    
    // StreamToolCallChecker checks if streaming output contains tool calls
    // Different models output tool calls differently in streaming mode
    // - OpenAI: outputs tool calls directly
    // - Claude: outputs text first, then tool calls
    // NOTE: Handler MUST close the stream before returning
    // Optional. Default: checks if first chunk contains tool calls
    // Aligns with: StreamToolCallChecker in react.go:82-95
    StreamToolCallChecker stream_tool_call_checker = nullptr;
    
    // GraphName is the name of the ReAct graph (for debugging)
    // Optional. Default: "ReActAgent"
    // Aligns with: GraphName in react.go:97-99
    std::string graph_name;
    
    // ModelNodeName is the name of the ChatModel node in the graph
    // Optional. Default: "ChatModel"
    // Aligns with: ModelNodeName in react.go:100-102
    std::string model_node_name;
    
    // ToolsNodeName is the name of the Tools node in the graph
    // Optional. Default: "Tools"
    // Aligns with: ToolsNodeName in react.go:103-105
    std::string tools_node_name;
    
    // AgentName is the name of the agent (for logging/debugging)
    std::string agent_name;
    
    // BeforeChatModel hooks executed before each ChatModel invocation
    std::vector<std::function<void(void*, ChatModelAgentState*)>> before_chat_model;
    
    // AfterChatModel hooks executed after each ChatModel invocation
    std::vector<std::function<void(void*, ChatModelAgentState*)>> after_chat_model;
    
    ReactConfig() = default;
};

// =============================================================================
// Public API Functions
// =============================================================================

/**
 * @brief Create a new ReAct graph
 * 
 * Creates a compiled Graph that implements the ReAct (Reasoning + Acting) pattern.
 * 
 * Graph structure:
 *   START -> chat (ChatModel) -> [branch]
 *                                   |
 *                                   +-> END (if no tool calls)
 *                                   |
 *                                   +-> tools -> [branch]
 *                                                 |
 *                                                 +-> direct_return -> END (if return_directly)
 *                                                 |
 *                                                 +-> chat (continue loop)
 * 
 * @param ctx Context for execution
 * @param config Configuration for ReAct agent
 * @return Compiled graph ready for execution, or nullptr on error
 * 
 * Aligns with: NewAgent() in react.go:174-272
 */
std::shared_ptr<compose::Graph<std::vector<schema::Message>, schema::Message>> NewReact(
    void* ctx,
    const ReactConfig& config);

/**
 * @brief Store tool generation action in state
 * 
 * Saves the action generated by the LLM for a specific tool call.
 * Used to track which tools were requested during reasoning.
 * 
 * @param ctx Context
 * @param tool_name Name or ID of the tool
 * @param action The action generated by the LLM
 * @return Empty string on success, error message on failure
 * 
 * Aligns with: SendToolGenAction in react.go:51-56
 */
std::string SendToolGenAction(
    void* ctx,
    const std::string& tool_name,
    std::shared_ptr<AgentAction> action);

/**
 * @brief Retrieve and remove tool generation action from state
 * 
 * Gets the action for a specific tool and removes it from state.
 * 
 * @param ctx Context
 * @param tool_name Name or ID of the tool
 * @return The action if found, nullptr otherwise
 * 
 * Aligns with: popToolGenAction in react.go:58-73
 */
std::shared_ptr<AgentAction> PopToolGenAction(
    void* ctx,
    const std::string& tool_name);

/**
 * @brief Get or create ReactState from session
 * 
 * Internal helper to manage ReactState lifecycle.
 * Creates new state if none exists.
 * 
 * @param ctx Context
 * @return Shared pointer to ReactState
 */
std::shared_ptr<ReactState> GetOrCreateReactState(void* ctx);

/**
 * @brief Get return_directly tool call ID from message
 * 
 * Checks if any tool calls in the message are marked as return_directly.
 * Returns the ID of the first such tool call found.
 * 
 * @param input Message containing tool calls
 * @param tool_return_directly Map of tool names to return_directly flags
 * @return Tool call ID if found, empty string otherwise
 * 
 * Aligns with: getReturnDirectlyToolCallID in react.go:341-353
 */
std::string GetReturnDirectlyToolCallID(
    const schema::Message* input,
    const std::map<std::string, bool>& tool_return_directly);

/**
 * @brief Build return_directly logic in graph
 * 
 * Internal helper that adds the direct_return node and routing logic.
 * Handles tools that should return their results immediately.
 * 
 * @param graph The graph to modify
 * @return Empty string on success, error message on failure
 * 
 * Aligns with: buildReturnDirectly in react.go:297-339
 */
std::string BuildReturnDirectly(
    compose::Graph<std::vector<schema::Message>, schema::Message>* graph);

// =============================================================================
// Session Keys for State Management
// =============================================================================

// Session key for storing ReactState
constexpr const char* kReactStateKey = "react_state";

}  // namespace adk
}  // namespace eino

#endif  // EINO_CPP_ADK_REACT_H_
