/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef EINO_CPP_ADK_TOOLS_H_
#define EINO_CPP_ADK_TOOLS_H_

// Agent Built-in Tools
// ====================
// Aligns with eino adk tools:
// - TransferToAgentTool: transfer execution to another agent
// - ExitTool: exit agent with final result

#include "../components/tool.h"
#include "../schema/types.h"
#include "types.h"
#include <string>
#include <memory>

namespace eino {
namespace adk {

// TransferToAgentTool - Tool for transferring to another agent
// Aligns with: eino/adk/chatmodel.go:320-347
class TransferToAgentTool : public components::BaseTool {
public:
    TransferToAgentTool() = default;
    ~TransferToAgentTool() override = default;

    // Info returns tool information
    // Aligns with: transferToAgent.Info() in chatmodel.go:322-324
    schema::ToolInfo Info(void* ctx) const override {
        schema::ToolInfo info;
        info.name = "transfer_to_agent";
        info.desc = "Transfer the question to another agent.";
        
        // Parameters
        info.params_one_of = schema::NewParamsOneOfByParams({
            {"agent_name", schema::ParameterInfo{
                .desc = "the name of the agent to transfer to",
                .required = true,
                .type = schema::String
            }}
        });
        
        return info;
    }

    // InvokableRun executes the tool
    // Aligns with: transferToAgent.InvokableRun() in chatmodel.go:330-346
    std::string InvokableRun(
        void* ctx, 
        const std::string& arguments_json,
        const std::vector<components::ToolOption>& options = {}) override;

    static constexpr const char* kToolName = "transfer_to_agent";
    static constexpr const char* kToolDesc = "Transfer the question to another agent.";
};

// ExitTool - Tool for exiting agent with final result
// Aligns with: eino/adk/chatmodel.go:295-318
class ExitTool : public components::BaseTool {
public:
    ExitTool() = default;
    ~ExitTool() override = default;

    // Info returns tool information
    // Aligns with: ExitTool.Info() in chatmodel.go:297-299
    schema::ToolInfo Info(void* ctx) const override {
        schema::ToolInfo info;
        info.name = "exit";
        info.desc = "Exit the agent process and return the final result.";
        
        // Parameters
        info.params_one_of = schema::NewParamsOneOfByParams({
            {"final_result", schema::ParameterInfo{
                .desc = "the final result to return",
                .required = true,
                .type = schema::String
            }}
        });
        
        return info;
    }

    // InvokableRun executes the tool
    // Aligns with: ExitTool.InvokableRun() in chatmodel.go:301-317
    std::string InvokableRun(
        void* ctx,
        const std::string& arguments_json,
        const std::vector<components::ToolOption>& options = {}) override;

    static constexpr const char* kToolName = "exit";
    static constexpr const char* kToolDesc = "Exit the agent process and return the final result.";
};

// Helper to create TransferToAgentAction
// Aligns with: NewTransferToAgentAction in eino/adk/interface.go
std::shared_ptr<AgentAction> NewTransferToAgentAction(const std::string& dest_agent_name);

// Helper to create ExitAction
// Aligns with: NewExitAction in eino/adk/interface.go
std::shared_ptr<AgentAction> NewExitAction();

// SendToolGenAction - Send action generated by tool to state
// Aligns with: eino/adk/react.go:51-60
std::string SendToolGenAction(
    void* ctx,
    const std::string& tool_name,
    std::shared_ptr<AgentAction> action);

// PopToolGenAction - Pop action generated by tool from state
// Aligns with: eino/adk/react.go:62-73
std::shared_ptr<AgentAction> PopToolGenAction(
    void* ctx,
    const std::string& tool_name);

}  // namespace adk
}  // namespace eino

#endif  // EINO_CPP_ADK_TOOLS_H_
